// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasportDetails.Models;

namespace PasportDetails.Migrations
{
    [DbContext(typeof(PDetailsContex))]
    [Migration("20200413061131_a")]
    partial class a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PasportDetails.Models.PDetails", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PPExp")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PPNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PPOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("PId");

                    b.ToTable("PDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
